# Generated by Django 5.1.3 on 2025-07-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waferapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelocnn",
            options={
                "verbose_name": "Modelo CNN",
                "verbose_name_plural": "Modelos CNN",
            },
        ),
    ]
