# Generated by Django 5.1.3 on 2025-07-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waferapp", "0002_imagensubida"),
        ("waferapp", "0003_historialprediccion"),
    ]

    operations = []
