# Generated by Django 5.1.3 on 2025-07-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waferapp", "0004_merge_0002_imagensubida_0003_historialprediccion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelocnn",
            options={},
        ),
    ]
